name: Build Plugin
on:
  push:
    tags:
      - 'alpha-*.*.*'
      - 'beta-*.*.*'
      - 'release-*.*.*'
jobs:
  Build-Plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
            java-version: '11'
            distribution: 'adopt'
      - name: Building plugin
        run: ./gradlew buildPlugin
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/distributions/AndroidBluePrint-*.zip
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}